const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const storeKey='horgasz_naplo_v2';
const old=JSON.parse(localStorage.getItem('horgasz_naplo_v1')||'{}');
const defaults={
  logs:old.logs||[], customWaters:old.customWaters||[],
  baits:[{name:'Wafter',category:'Lebegő csali',img:'assets/fish/ponty.webp',note:'Method és feeder horgászathoz.'},{name:'Pellet',category:'Süllyedő csali',img:'assets/fish/amur.webp',note:'Ponty, amur, kárász.'},{name:'Kukorica',category:'Mag / természetes',img:'assets/fish/karasz.webp',note:'Általános békéshalas csali.'}],
  feeds:[{name:'Method mix',category:'Etetőanyag',img:'assets/waters/intenziv-viz.webp',note:'Method kosárhoz.'},{name:'Fűszeres pontyos',category:'Etetőanyag',img:'assets/waters/banyato.webp',note:'Pontyra, amurra.'}],
  hooks:[{name:'Guru QM1 #10',category:'Horog',img:'assets/fish/ponty.webp',size:'#10',note:'Method feederhez.'},{name:'Owner Iseama #8',category:'Horog',img:'assets/fish/harcsa.webp',size:'#8',note:'Erős, univerzális horog.'}],
  methods:[{name:'Method feeder',category:'Fenék',img:'assets/waters/derito-to.webp',note:'Kosaras feeder technika.'},{name:'Feeder',category:'Fenék',img:'assets/waters/tisza-to.webp',note:'Általános feeder módszer.'},{name:'Úszós',category:'Úszós',img:'assets/waters/holtag.webp',note:'Partközeli és finom módszer.'},{name:'Pergetés',category:'Ragadozó',img:'assets/fish/csuka.webp',note:'Műcsalis horgászat.'}]
};
let state=JSON.parse(localStorage.getItem(storeKey)||JSON.stringify(defaults));
for(const k of Object.keys(defaults)) if(!state[k]) state[k]=defaults[k];
let draft={water:null,waterImg:null,fish:[],baits:[],feeds:[],hooks:[],method:null,weather:null};
function save(){localStorage.setItem(storeKey,JSON.stringify(state));}
function switchView(v){$$('.side button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));$$('.view').forEach(x=>x.classList.remove('show'));$('#view-'+v).classList.add('show'); render(v)}
$$('.side button').forEach(b=>b.onclick=()=>switchView(b.dataset.view));
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function card(item,type){return `<div class="card-img" data-type="${type}" data-name="${esc(item.name)}"><img src="${item.img}" alt="${esc(item.name)}"><span class="badge">${type==='fish'?'🐟':type==='water'?'📍':type==='hook'?'🪝':'🎣'}</span></div>`}
function chipItem(item,type){return `<div class="mini-card" data-type="${type}" data-name="${esc(item.name)}"><img src="${item.img}"><b>${esc(item.name)}</b><small>${esc(item.category||item.size||'')}</small></div>`}
function filterCards(sel,q){q=q.toLowerCase();$$(sel+' [data-name]').forEach(c=>c.style.display=c.dataset.name.toLowerCase().includes(q)?'':'none')}
function fileToData(file){return new Promise(r=>{let fr=new FileReader();fr.onload=()=>r(fr.result);fr.readAsDataURL(file)})}
function parseCoords(txt){let m=(txt||'').match(/(-?\d+(?:\.\d+)?)\s*[,; ]\s*(-?\d+(?:\.\d+)?)/);return m?{lat:+m[1],lon:+m[2]}:null}
function directionText(deg){if(deg==null)return 'n/a';const dirs=['É','ÉK','K','DK','D','DNY','NY','ÉNY'];return dirs[Math.round(((deg%360)/45))%8]+` (${Math.round(deg)}°)`}
function weatherCodeText(code){const m={0:'Derült',1:'Többnyire derült',2:'Részben felhős',3:'Borult',45:'Köd',48:'Zúzmarás köd',51:'Gyenge szitálás',53:'Szitálás',55:'Erős szitálás',61:'Gyenge eső',63:'Eső',65:'Erős eső',71:'Gyenge hó',73:'Hó',75:'Erős hó',80:'Zápor',81:'Zápor',82:'Erős zápor',95:'Zivatar'};return m[code]||`Kód: ${code}`}
function moonPhase(date=new Date()){const lp=2551443,now=date.getTime()/1000,nm=new Date('2001-01-24T13:07:00Z').getTime()/1000,ph=((now-nm)%lp)/lp,names=['Újhold','Növő holdsarló','Első negyed','Növő hold','Telihold','Fogyó hold','Utolsó negyed','Fogyó holdsarló'];return {name:names[Math.floor(ph*8+.5)%8],illumination:Math.round((1-Math.cos(ph*2*Math.PI))/2*100)}}
function nearestIndex(times,t){if(!times||!times.length)return 0;let trg=new Date(t||Date.now()).getTime(),b=0,d=1e18;times.forEach((x,i)=>{let dd=Math.abs(new Date(x).getTime()-trg);if(dd<d){d=dd;b=i}});return b}
function fishingScore(w){if(!w)return{score:0,label:'nincs adat',tips:[]};let sc=50,t=[];if(w.pressure>=1008&&w.pressure<=1020){sc+=10;t.push('kedvező légnyomás')}if(w.wind>=5&&w.wind<=22){sc+=10;t.push('jó szélmozgás')}if(w.gust>35){sc-=12;t.push('erős széllökés')}if(w.pressure>1030||w.pressure<995){sc-=8;t.push('szélsőséges légnyomás')}sc=Math.max(0,Math.min(100,Math.round(sc)));return{score:sc,label:sc>=70?'jó':sc>=45?'közepes':'gyenge',tips:t}}
async function getWeather(lat,lon){let cur='temperature_2m,apparent_temperature,relative_humidity_2m,precipitation,rain,showers,weather_code,cloud_cover,surface_pressure,pressure_msl,wind_speed_10m,wind_gusts_10m,wind_direction_10m';let hourly='temperature_2m,apparent_temperature,relative_humidity_2m,precipitation_probability,precipitation,weather_code,cloud_cover,surface_pressure,pressure_msl,wind_speed_10m,wind_gusts_10m,wind_direction_10m,uv_index,is_day';let daily='sunrise,sunset,daylight_duration,precipitation_sum,precipitation_probability_max,wind_speed_10m_max,wind_gusts_10m_max';let url=`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=${cur}&hourly=${hourly}&daily=${daily}&forecast_days=3&timezone=auto&wind_speed_unit=kmh&precipitation_unit=mm`;
  let r=await fetch(url); if(!r.ok) throw Error('weather'); let j=await r.json(),h=j.hourly||{},c=j.current||{},i=nearestIndex(h.time,c.time);
  let w={provider:'Open-Meteo',lat,lon,timezone:j.timezone,elevation:j.elevation,fetchedAt:new Date().toISOString(),time:c.time,temp:c.temperature_2m,feels:c.apparent_temperature,humidity:c.relative_humidity_2m,precip:c.precipitation,rain:c.rain,showers:c.showers,code:c.weather_code,weatherText:weatherCodeText(c.weather_code),cloud:c.cloud_cover,surfacePressure:c.surface_pressure,pressure:c.pressure_msl,wind:c.wind_speed_10m,gust:c.wind_gusts_10m,windDir:c.wind_direction_10m,precipProb:h.precipitation_probability?.[i]??null,uv:h.uv_index?.[i]??null,isDay:h.is_day?.[i]??null,daily:j.daily||{},hourly:{time:h.time?.slice(0,24),temp:h.temperature_2m?.slice(0,24),precipProb:h.precipitation_probability?.slice(0,24),wind:h.wind_speed_10m?.slice(0,24)},moon:moonPhase(new Date()),sourceUrl:url};w.score=fishingScore(w);return w}
function weatherText(w){if(!w)return 'Nincs időjárás adat';return `${w.temp}°C · ${w.weatherText||''} · szél ${w.wind} km/h ${directionText(w.windDir)} · páratartalom ${w.humidity}% · légnyomás ${w.pressure} hPa`}
function weatherPanel(w){if(!w)return `<div class="weather-empty">Nincs lekért időjárás. GPS vagy koordináta alapján kérd le, majd mentéskor az adatok is bekerülnek a naplóba.</div>`;let sc=w.score||fishingScore(w);return `<div class="weather-full"><div class="weather-head"><div><small>${esc(w.provider||'Open-Meteo')} · ${esc(w.time||'')}</small><h2>${w.temp}°C <span>${esc(w.weatherText||'')}</span></h2></div><div class="score"><b>${sc.score}</b><small>/100 · ${sc.label}</small></div></div><div class="stat weather-stat"><div><b>${w.feels??'--'}°C</b><br>hőérzet</div><div><b>${w.humidity??'--'}%</b><br>páratartalom</div><div><b>${w.pressure??'--'} hPa</b><br>tengerszinti légnyomás</div><div><b>${w.surfacePressure??'--'} hPa</b><br>felszíni légnyomás</div><div><b>${w.wind??'--'} km/h</b><br>szél</div><div><b>${directionText(w.windDir)}</b><br>szélirány</div><div><b>${w.gust??'--'} km/h</b><br>széllökés</div><div><b>${w.cloud??'--'}%</b><br>felhőzet</div><div><b>${w.precip??'--'} mm</b><br>csapadék</div><div><b>${w.precipProb??'--'}%</b><br>csapadék esély</div><div><b>${w.uv??'--'}</b><br>UV index</div><div><b>${w.moon?.name||'--'} (${w.moon?.illumination??'--'}%)</b><br>hold</div></div><p class="hint">${sc.tips.length?'Megjegyzés: '+esc(sc.tips.join(', ')):'A pontszám csak naplózási segédlet.'}</p></div>`}
function showSideWeather(w){$('#sideWeather').innerHTML=w?`<small>Élő időjárás</small><h2>${w.temp}°C</h2><p>${w.wind} km/h szél<br>${w.humidity}% páratartalom<br>${w.pressure} hPa</p>`:`<small>Élő időjárás</small><h2>--°C</h2><p>Adj meg koordinátát vagy engedélyezd a GPS-t.</p>`}
function weatherPanel(w){return `<div class="stat"><div><b>${w? w.temp+'°C':'--'}</b><br>hőmérséklet</div><div><b>${w? w.wind+' km/h':'--'}</b><br>szél</div><div><b>${w? w.pressure+' hPa':'--'}</b><br>légnyomás</div><div><b>${w? w.humidity+'%':'--'}</b><br>páratartalom</div><div><b>${w? w.precip+' mm':'--'}</b><br>csapadék</div><div><b>${w? w.time:'--'}</b><br>lekérés ideje</div></div>`}
function allWaters(){return [...WATER_DATA,...state.customWaters]}
function renderNew(){const waters=allWaters();$('#view-new').innerHTML=`<div class="panel"><h2>Új horgászat rögzítése</h2><div class="form-grid"><div><h3>Alap adatok</h3><label class="field">Dátum<input id="date" type="date" value="${new Date().toISOString().slice(0,10)}"></label><label class="field">Idő<input id="time" type="time" value="06:30"></label><label class="field">Módszer<select id="method"><option value="">Válassz módszert</option>${state.methods.map(m=>`<option>${esc(m.name)}</option>`).join('')}</select></label><label class="field">Megjegyzés<textarea id="note" rows="5" placeholder="Mi történt a túrán?"></textarea></label></div><div><h3>Élő időjárás</h3><div id="weatherBox">${weatherPanel(draft.weather)}</div><label class="field">Koordináta<input id="coords" placeholder="47.2487, 18.6208"></label><div class="row"><button class="btn muted" id="gpsBtn">GPS használata</button><button class="btn primary" id="weatherBtn">Időjárás lekérése</button></div><label class="field">Víz hőmérséklet<input id="waterTemp" placeholder="pl. 16.5 °C"></label><label class="field">Víz színe<select id="waterColor"><option>Enyhén zavaros</option><option>Tiszta</option><option>Zavaros</option><option>Sötét</option></select></label></div><div><h3>Vízterület</h3><input class="search" id="waterSearch" placeholder="Keresés vízterületek között"><div class="thumbs" id="waterThumbs">${waters.map(w=>`<img src="${w.img}" title="${esc(w.name)}" data-name="${esc(w.name)}" data-img="${w.img}" data-coords="${[w.lat,w.lon].filter(Boolean).join(', ')}">`).join('')}</div><label class="field">Saját hely neve<input id="customWaterName" placeholder="pl. kedvenc stég"></label><label class="field">Saját kép<input id="customWaterPhoto" type="file" accept="image/*"></label><button class="btn muted" id="addCustomWater">Saját hely hozzáadása</button></div></div></div><div class="panel"><h3>Halfaj kiválasztása</h3><input class="search" id="fishSearch" placeholder="Keresés halfajok között"><div class="grid" id="fishPick">${FISH_DATA.map(f=>card(f,'fish')).join('')}</div></div>${pickSection('Csalik','baits',state.baits)}${pickSection('Etetőanyagok','feeds',state.feeds)}${pickSection('Horgok','hooks',state.hooks)}<div class="panel"><h3>Képek és mentés</h3><label class="field">Túra képei<input id="tripPhotos" type="file" accept="image/*" multiple></label><button class="btn primary" id="saveLog">Napló mentése</button> <button class="btn muted" id="cancelBtn">Mégsem</button></div>`;
$('#waterThumbs').onclick=e=>{if(e.target.tagName==='IMG'){draft.water=e.target.dataset.name;draft.waterImg=e.target.dataset.img;$$('#waterThumbs img').forEach(i=>i.classList.toggle('on',i===e.target)); if(e.target.dataset.coords) $('#coords').value=e.target.dataset.coords;}};
$('#fishPick').onclick=e=>togglePick(e,'fish'); ['baits','feeds','hooks'].forEach(k=>{$('#pick-'+k).onclick=e=>togglePick(e,k)});
$('#method').onchange=e=>draft.method=e.target.value;
$('#fishSearch').oninput=e=>filterCards('#fishPick',e.target.value); $('#waterSearch').oninput=e=>{let q=e.target.value.toLowerCase();$$('#waterThumbs img').forEach(i=>i.style.display=i.title.toLowerCase().includes(q)?'':'none')};
$('#gpsBtn').onclick=()=>navigator.geolocation?navigator.geolocation.getCurrentPosition(pos=>{$('#coords').value=`${pos.coords.latitude.toFixed(6)}, ${pos.coords.longitude.toFixed(6)}`},()=>alert('Nem sikerült GPS pozíciót kérni.')):alert('A böngésző nem támogatja a GPS lekérést.');
$('#weatherBtn').onclick=async()=>{let c=parseCoords($('#coords').value); if(!c)return alert('Adj meg koordinátát: szélesség, hosszúság'); try{draft.weather=await getWeather(c.lat,c.lon); $('#weatherBox').innerHTML=weatherPanel(draft.weather); showSideWeather(draft.weather)}catch(e){alert('Az időjárás lekérése nem sikerült. Internetkapcsolat kell hozzá.')}};
$('#addCustomWater').onclick=async()=>{let f=$('#customWaterPhoto').files[0], name=$('#customWaterName').value.trim(); if(!name)return alert('Adj nevet a saját helynek.'); let img=f?await fileToData(f):'assets/waters/csatorna.webp'; let c=parseCoords($('#coords').value)||{}; state.customWaters.push({name,img,lat:c.lat||'',lon:c.lon||''}); save(); switchView('new')};
$('#saveLog').onclick=async()=>{let photos=[];for(const f of $('#tripPhotos').files)photos.push(await fileToData(f));let log={id:Date.now(),date:$('#date').value,time:$('#time').value,method:$('#method').value,water:draft.water||$('#customWaterName').value||'Nincs megadva',waterImg:draft.waterImg||findWaterImg(draft.water),coords:$('#coords').value,weather:draft.weather,note:$('#note').value,waterTemp:$('#waterTemp').value,waterColor:$('#waterColor').value,fish:draft.fish,baits:draft.baits,feeds:draft.feeds,hooks:draft.hooks,photos};state.logs.unshift(log);save();draft={water:null,waterImg:null,fish:[],baits:[],feeds:[],hooks:[],method:null,weather:null};switchView('logs')};
$('#cancelBtn').onclick=()=>{draft={water:null,waterImg:null,fish:[],baits:[],feeds:[],hooks:[],method:null,weather:null};switchView('new')}
}
function pickSection(title,key,items){return `<div class="panel"><h3>${title}</h3><input class="search" oninput="filterCards('#pick-${key}',this.value)" placeholder="Keresés"><div class="mini-grid" id="pick-${key}">${items.map(i=>chipItem(i,key)).join('')}</div></div>`}
function togglePick(e,key){let c=e.target.closest('[data-name]'); if(!c)return; let n=c.dataset.name; c.classList.toggle('selected'); let arr=key==='fish'?draft.fish:draft[key]; if(c.classList.contains('selected')) arr.push(n); else {let ix=arr.indexOf(n); if(ix>-1)arr.splice(ix,1)} }
function findWaterImg(n){let w=allWaters().find(x=>x.name===n);return w?w.img:'assets/waters/csatorna.webp'}
function renderLogs(){let logs=state.logs;$('#view-logs').innerHTML=`<div class="panel"><h2>Mentett horgászatok</h2>${logs.length?'':'<p>Még nincs mentett napló.</p>'}${logs.map(l=>`<div class="list-item"><img src="${(l.photos&&l.photos[0])||l.waterImg||findWaterImg(l.water)}"><div><b>${esc(l.date)} ${esc(l.time)} – ${esc(l.water)}</b><br>${esc(l.method||'nincs módszer')} · ${esc((l.fish||[]).join(', ')||'nincs fogás')}<br><small>${esc(weatherText(l.weather))}</small></div><button class="btn primary" onclick="showLog(${l.id})">Megnyitás</button><button class="btn danger" onclick="delLog(${l.id})">Törlés</button></div>`).join('')}</div>`}
function showLog(id){let l=state.logs.find(x=>x.id===id); modal(`<h2>${esc(l.date)} ${esc(l.time)} – ${esc(l.water)}</h2><img src="${(l.photos&&l.photos[0])||l.waterImg||findWaterImg(l.water)}"><h3>Időjárás</h3>${weatherPanel(l.weather)}<h3>Adatok</h3><p><b>Módszer:</b> ${esc(l.method||'')}</p><p><b>Koordináta:</b> ${esc(l.coords||'')}</p><p><b>Víz:</b> ${esc(l.waterColor||'')} · ${esc(l.waterTemp||'')}</p><p><b>Halak:</b> ${esc((l.fish||[]).join(', '))}</p><p><b>Csalik:</b> ${esc((l.baits||[]).join(', '))}</p><p><b>Etetőanyag:</b> ${esc((l.feeds||[]).join(', '))}</p><p><b>Horgok:</b> ${esc((l.hooks||[]).join(', '))}</p><p><b>Jegyzet:</b><br>${esc(l.note||'')}</p>${(l.photos||[]).map(p=>`<img src="${p}">`).join('')}`)}
function delLog(id){if(confirm('Törlöd ezt a naplót?')){state.logs=state.logs.filter(l=>l.id!==id);save();renderLogs()}}
function modal(html){if(!$('#modal'))document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="modal"><div class="box"><button class="btn muted" onclick="$('#modal').classList.remove('show')">Bezárás</button><div id="modalBody"></div></div></div>`);$('#modalBody').innerHTML=html;$('#modal').classList.add('show')}
function renderFish(){ $('#view-fish').innerHTML=`<div class="panel"><h2>Halfajok</h2><input class="search" id="fishListSearch" placeholder="Keresés halfaj szerint"><div class="grid" id="fishList">${FISH_DATA.map(f=>card(f,'fish')).join('')}</div><p><b>Figyelem:</b> a tilalmi idő és méretkorlát induló adat, mindig ellenőrizd az aktuális országos és helyi horgászrendet.</p></div>`;$('#fishListSearch').oninput=e=>filterCards('#fishList',e.target.value);$('#fishList').onclick=e=>{let c=e.target.closest('.card-img');if(!c)return;let f=FISH_DATA.find(x=>x.name===c.dataset.name);modal(`<h2>${esc(f.name)}</h2><img src="${f.img}"><p><i>${esc(f.latin)}</i></p><div class="stat"><div><b>Tilalom</b><br>${esc(f.ban)}</div><div><b>Méret</b><br>${esc(f.size)}</div><div><b>Fontos</b><br>helyi szabály ellenőrzendő</div></div><p>${esc(f.info)}</p>`)}}
function renderWaters(){let all=allWaters();$('#view-waters').innerHTML=`<div class="panel"><h2>Vízterületek</h2><p>Itt a beépített és saját vízterületek látszanak. Új saját helyet az Új napló képernyőn tudsz felvenni képpel és koordinátával.</p><input class="search" id="waterListSearch" placeholder="Keresés"><div class="grid" id="waterList">${all.map(w=>card(w,'water')).join('')}</div></div>`;$('#waterListSearch').oninput=e=>filterCards('#waterList',e.target.value)}
function renderManage(key,title){let items=state[key];$('#view-'+key).innerHTML=`<div class="panel"><h2>${title} adatbázis</h2><div class="form-grid"><div><label class="field">Név<input id="mName"></label><label class="field">Kategória / méret<input id="mCat"></label><label class="field">Megjegyzés<textarea id="mNote"></textarea></label><label class="field">Kép<input id="mImg" type="file" accept="image/*"></label><button class="btn primary" id="mAdd">Hozzáadás</button></div><div style="grid-column:span 2"><input class="search" id="mSearch" placeholder="Keresés"><div class="mini-grid" id="mList">${items.map((i,idx)=>`<div class="mini-card"><img src="${i.img}"><b>${esc(i.name)}</b><small>${esc(i.category||i.size||'')}</small><p>${esc(i.note||'')}</p><button class="btn danger" onclick="deleteItem('${key}',${idx})">Törlés</button></div>`).join('')}</div></div></div></div>`;$('#mSearch').oninput=e=>filterCards('#mList',e.target.value);$('#mAdd').onclick=async()=>{let name=$('#mName').value.trim();if(!name)return alert('Adj nevet.');let f=$('#mImg').files[0];let img=f?await fileToData(f):'assets/waters/intenziv-viz.webp';state[key].push({name,category:$('#mCat').value,note:$('#mNote').value,img});save();renderManage(key,title)}}
function deleteItem(key,idx){if(confirm('Törlöd?')){state[key].splice(idx,1);save();renderManage(key,{baits:'Csalik',feeds:'Etetőanyagok',hooks:'Horgok',methods:'Módszerek'}[key])}}
function renderStats(){let logs=state.logs||[];let totalKg=logs.reduce((a,l)=>a+(l.catches||[]).reduce((sum,c)=>sum+(+c.weight||0)*(+c.count||1),0),0);let fish={},methods={};logs.forEach(l=>{(l.catches||[]).forEach(c=>fish[c.fish]=(fish[c.fish]||0)+(+c.count||1));if(l.method)methods[l.method]=(methods[l.method]||0)+1});let top=o=>Object.entries(o).sort((a,b)=>b[1]-a[1]).slice(0,8);$('#view-stats').innerHTML=`<div class="panel"><h2>Statisztikák</h2><div class="stat"><div><b>${logs.length}</b><br>horgászat</div><div><b>${totalKg.toFixed(2)} kg</b><br>rögzített össztömeg</div><div><b>${Object.keys(fish).length}</b><br>halfaj</div></div></div><div class="panel"><h3>Leggyakoribb halfajok</h3>${bars(top(fish))}</div><div class="panel"><h3>Módszerek</h3>${bars(top(methods))}</div>`}
function bars(arr){if(!arr.length)return '<p>Nincs adat.</p>';let m=Math.max(...arr.map(x=>x[1]),1);return arr.map(([n,v])=>`<div class="bar-row"><span>${esc(n)}</span><div><i style="width:${(v/m*100).toFixed(0)}%"></i></div><b>${v}</b></div>`).join('')}
function renderData(){ $('#view-data').innerHTML=`<div class="panel"><h2>Mentés / betöltés</h2><p>Az adatok ezen a telefonon/böngészőben mentődnek. Exportáld JSON-be, hogy később visszatölthesd vagy másik készülékre átvihesd.</p><button class="btn primary" id="exportBtn">JSON export</button><label class="field">JSON import<input id="importFile" type="file" accept="application/json"></label><textarea id="rawData" rows="10" style="width:100%">${esc(JSON.stringify(state,null,2))}</textarea></div>`;$('#exportBtn').onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='horgasz-naplo-mentes.json';a.click()};$('#importFile').onchange=e=>{let f=e.target.files[0];let fr=new FileReader();fr.onload=()=>{state=JSON.parse(fr.result);save();alert('Betöltve.');switchView('logs')};fr.readAsText(f)}}
function render(v){({new:renderNew,logs:renderLogs,fish:renderFish,waters:renderWaters,baits:()=>renderManage('baits','Csalik'),feeds:()=>renderManage('feeds','Etetőanyagok'),hooks:()=>renderManage('hooks','Horgok'),methods:()=>renderManage('methods','Módszerek'),stats:renderStats,data:renderData}[v])()}
switchView('new');
