const SEED_DATA = {
  "fish": [
    {
      "id": "angolna",
      "name": "Angolna",
      "latin": "Anguilla anguilla",
      "origin": "idegenhonos / telepített",
      "group": "vándorló",
      "invasive": false,
      "image": "assets/fish/angolna.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "",
      "dailyLimit": "",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "bodorka",
      "name": "Bodorka",
      "latin": "Rutilus rutilus",
      "origin": "őshonos",
      "group": "békés",
      "invasive": false,
      "image": "assets/fish/bodorka.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "",
      "dailyLimit": "",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "vorosszarnyu-keszeg",
      "name": "Vörösszárnyú keszeg",
      "latin": "Scardinius erythrophthalmus",
      "origin": "őshonos",
      "group": "békés",
      "invasive": false,
      "image": "assets/fish/vorosszarnyu-keszeg.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "",
      "dailyLimit": "",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "domolyko",
      "name": "Domolykó",
      "latin": "Squalius cephalus",
      "origin": "őshonos",
      "group": "békés",
      "invasive": false,
      "image": "assets/fish/domolyko.jpg",
      "closedStart": "04-15",
      "closedEnd": "05-31",
      "minSize": "25 cm",
      "dailyLimit": "3 kg",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "jaszkeszeg",
      "name": "Jászkeszeg",
      "latin": "Leuciscus idus",
      "origin": "őshonos",
      "group": "békés",
      "invasive": false,
      "image": "assets/fish/jaszkeszeg.jpg",
      "closedStart": "04-15",
      "closedEnd": "05-31",
      "minSize": "20 cm",
      "dailyLimit": "3 kg",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "nyuldomolyko",
      "name": "Nyúldomolykó",
      "latin": "Leuciscus leuciscus",
      "origin": "őshonos",
      "group": "békés",
      "invasive": false,
      "image": "assets/fish/nyuldomolyko.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "",
      "dailyLimit": "",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "kusz",
      "name": "Küsz",
      "latin": "Alburnus alburnus",
      "origin": "őshonos",
      "group": "békés",
      "invasive": false,
      "image": "assets/fish/kusz.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "",
      "dailyLimit": "",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "sujtasos-kusz",
      "name": "Sujtásos küsz",
      "latin": "Alburnoides bipunctatus",
      "origin": "őshonos / védett",
      "group": "védett",
      "invasive": false,
      "image": "assets/fish/sujtasos-kusz.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "",
      "dailyLimit": "",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "karikakeszeg",
      "name": "Karikakeszeg",
      "latin": "Blicca bjoerkna",
      "origin": "őshonos",
      "group": "békés",
      "invasive": false,
      "image": "assets/fish/karikakeszeg.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "",
      "dailyLimit": "",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "deverkeszeg",
      "name": "Dévérkeszeg",
      "latin": "Abramis brama",
      "origin": "őshonos",
      "group": "békés",
      "invasive": false,
      "image": "assets/fish/deverkeszeg.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "",
      "dailyLimit": "",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "laposkeszeg",
      "name": "Laposkeszeg",
      "latin": "Ballerus ballerus",
      "origin": "őshonos",
      "group": "békés",
      "invasive": false,
      "image": "assets/fish/laposkeszeg.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "",
      "dailyLimit": "",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "bagolykeszeg",
      "name": "Bagolykeszeg",
      "latin": "Ballerus sapa",
      "origin": "őshonos",
      "group": "békés",
      "invasive": false,
      "image": "assets/fish/bagolykeszeg.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "",
      "dailyLimit": "",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "szilvaorru-keszeg",
      "name": "Szilvaorrú keszeg",
      "latin": "Vimba vimba",
      "origin": "őshonos",
      "group": "békés",
      "invasive": false,
      "image": "assets/fish/szilvaorru-keszeg.jpg",
      "closedStart": "04-15",
      "closedEnd": "05-31",
      "minSize": "20 cm",
      "dailyLimit": "3 kg",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "garda",
      "name": "Garda",
      "latin": "Pelecus cultratus",
      "origin": "őshonos",
      "group": "békés",
      "invasive": false,
      "image": "assets/fish/garda.jpg",
      "closedStart": "04-15",
      "closedEnd": "05-31",
      "minSize": "20 cm",
      "dailyLimit": "3 kg",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "paduc",
      "name": "Paduc",
      "latin": "Chondrostoma nasus",
      "origin": "őshonos",
      "group": "békés",
      "invasive": false,
      "image": "assets/fish/paduc.jpg",
      "closedStart": "04-15",
      "closedEnd": "05-31",
      "minSize": "20 cm",
      "dailyLimit": "3 kg",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "marna",
      "name": "Márna",
      "latin": "Barbus barbus",
      "origin": "őshonos",
      "group": "békés",
      "invasive": false,
      "image": "assets/fish/marna.jpg",
      "closedStart": "04-15",
      "closedEnd": "05-31",
      "minSize": "40 cm",
      "dailyLimit": "3 db",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "petenyi-marna",
      "name": "Petényi-márna",
      "latin": "Barbus petenyi",
      "origin": "őshonos / védett",
      "group": "védett",
      "invasive": false,
      "image": "assets/fish/petenyi-marna.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "nem fogható / védett",
      "dailyLimit": "0",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "fenekjaro-kullo",
      "name": "Fenékjáró küllő",
      "latin": "Gobio gobio",
      "origin": "őshonos",
      "group": "békés",
      "invasive": false,
      "image": "assets/fish/fenekjaro-kullo.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "",
      "dailyLimit": "",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "halvanyfoltu-kullo",
      "name": "Halványfoltú küllő",
      "latin": "Romanogobio vladykovi",
      "origin": "őshonos / védett",
      "group": "védett",
      "invasive": false,
      "image": "assets/fish/halvanyfoltu-kullo.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "nem fogható / védett",
      "dailyLimit": "0",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "homoki-kullo",
      "name": "Homoki küllő",
      "latin": "Romanogobio kesslerii",
      "origin": "őshonos / védett",
      "group": "védett",
      "invasive": false,
      "image": "assets/fish/homoki-kullo.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "nem fogható / védett",
      "dailyLimit": "0",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "felpillanto-kullo",
      "name": "Felpillantó küllő",
      "latin": "Romanogobio uranoscopus",
      "origin": "őshonos / védett",
      "group": "védett",
      "invasive": false,
      "image": "assets/fish/felpillanto-kullo.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "nem fogható / védett",
      "dailyLimit": "0",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "penzes-per",
      "name": "Pénzes pér",
      "latin": "Thymallus thymallus",
      "origin": "őshonos / védett",
      "group": "védett",
      "invasive": false,
      "image": "assets/fish/penzes-per.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "nem fogható / védett",
      "dailyLimit": "0",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "ponty",
      "name": "Ponty",
      "latin": "Cyprinus carpio",
      "origin": "őshonos / telepített",
      "group": "békés",
      "invasive": false,
      "image": "assets/fish/ponty.jpg",
      "closedStart": "05-04",
      "closedEnd": "05-29",
      "minSize": "30 cm",
      "dailyLimit": "3 db",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "vadponty",
      "name": "Vadponty",
      "latin": "Cyprinus carpio morpha hungaricus",
      "origin": "őshonos / védett",
      "group": "védett",
      "invasive": false,
      "image": "assets/fish/vadponty.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "",
      "dailyLimit": "",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "compo",
      "name": "Compó",
      "latin": "Tinca tinca",
      "origin": "őshonos",
      "group": "békés",
      "invasive": false,
      "image": "assets/fish/compo.jpg",
      "closedStart": "05-04",
      "closedEnd": "06-15",
      "minSize": "25 cm",
      "dailyLimit": "3 db",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "karasz",
      "name": "Kárász",
      "latin": "Carassius carassius",
      "origin": "őshonos",
      "group": "békés",
      "invasive": false,
      "image": "assets/fish/karasz.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "",
      "dailyLimit": "",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "ezustkarasz",
      "name": "Ezüstkárász",
      "latin": "Carassius gibelio",
      "origin": "inváziós / idegenhonos",
      "group": "inváziós",
      "invasive": true,
      "image": "assets/fish/ezustkarasz.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "",
      "dailyLimit": "",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "amur",
      "name": "Amur",
      "latin": "Ctenopharyngodon idella",
      "origin": "idegenhonos / telepített",
      "group": "békés",
      "invasive": false,
      "image": "assets/fish/amur.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "",
      "dailyLimit": "",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "feher-busa",
      "name": "Fehér busa",
      "latin": "Hypophthalmichthys molitrix",
      "origin": "idegenhonos / telepített",
      "group": "békés",
      "invasive": false,
      "image": "assets/fish/feher-busa.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "",
      "dailyLimit": "",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "pettyes-busa",
      "name": "Pettyes busa",
      "latin": "Hypophthalmichthys nobilis",
      "origin": "idegenhonos / telepített",
      "group": "békés",
      "invasive": false,
      "image": "assets/fish/pettyes-busa.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "",
      "dailyLimit": "",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "reti-csik",
      "name": "Réti csík",
      "latin": "Misgurnus fossilis",
      "origin": "őshonos / védett",
      "group": "védett",
      "invasive": false,
      "image": "assets/fish/reti-csik.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "nem fogható / védett",
      "dailyLimit": "0",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "vagocsik",
      "name": "Vágócsík",
      "latin": "Cobitis elongatoides",
      "origin": "őshonos / védett",
      "group": "védett",
      "invasive": false,
      "image": "assets/fish/vagocsik.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "",
      "dailyLimit": "",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "balkani-csik",
      "name": "Balkáni csík",
      "latin": "Sabanejewia balcanica",
      "origin": "őshonos / védett",
      "group": "védett",
      "invasive": false,
      "image": "assets/fish/balkani-csik.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "",
      "dailyLimit": "",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "tarka-geb",
      "name": "Tarka géb",
      "latin": "Proterorhinus semilunaris",
      "origin": "idegenhonos",
      "group": "inváziós",
      "invasive": true,
      "image": "assets/fish/tarka-geb.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "",
      "dailyLimit": "",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "feketeszaju-geb",
      "name": "Feketeszájú géb",
      "latin": "Neogobius melanostomus",
      "origin": "inváziós / idegenhonos",
      "group": "inváziós",
      "invasive": true,
      "image": "assets/fish/feketeszaju-geb.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "",
      "dailyLimit": "",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "csupasztorku-geb",
      "name": "Csupasztorkú géb",
      "latin": "Babka gymnotrachelus",
      "origin": "inváziós / idegenhonos",
      "group": "inváziós",
      "invasive": true,
      "image": "assets/fish/csupasztorku-geb.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "",
      "dailyLimit": "",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "kerekfeju-geb",
      "name": "Kerekfejű géb",
      "latin": "Neogobius fluviatilis",
      "origin": "inváziós / idegenhonos",
      "group": "inváziós",
      "invasive": true,
      "image": "assets/fish/kerekfeju-geb.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "",
      "dailyLimit": "",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "kessler-geb",
      "name": "Kessler-géb",
      "latin": "Ponticola kessleri",
      "origin": "inváziós / idegenhonos",
      "group": "inváziós",
      "invasive": true,
      "image": "assets/fish/kessler-geb.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "",
      "dailyLimit": "",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "suger",
      "name": "Sügér",
      "latin": "Perca fluviatilis",
      "origin": "őshonos",
      "group": "ragadozó",
      "invasive": false,
      "image": "assets/fish/suger.jpg",
      "closedStart": "03-02",
      "closedEnd": "04-30",
      "minSize": "15 cm",
      "dailyLimit": "3 kg",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "vagodurbincs",
      "name": "Vágódurbincs",
      "latin": "Gymnocephalus cernua",
      "origin": "őshonos",
      "group": "ragadozó",
      "invasive": false,
      "image": "assets/fish/vagodurbincs.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "",
      "dailyLimit": "",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "selymes-durbincs",
      "name": "Selymes durbincs",
      "latin": "Gymnocephalus schraetser",
      "origin": "őshonos / védett",
      "group": "védett",
      "invasive": false,
      "image": "assets/fish/selymes-durbincs.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "nem fogható / védett",
      "dailyLimit": "0",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "szeles-durbincs",
      "name": "Széles durbincs",
      "latin": "Gymnocephalus baloni",
      "origin": "őshonos / védett",
      "group": "védett",
      "invasive": false,
      "image": "assets/fish/szeles-durbincs.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "",
      "dailyLimit": "",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "magyar-buco",
      "name": "Magyar bucó",
      "latin": "Zingel zingel",
      "origin": "őshonos / védett",
      "group": "védett",
      "invasive": false,
      "image": "assets/fish/magyar-buco.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "nem fogható / védett",
      "dailyLimit": "0",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "nemet-buco",
      "name": "Német bucó",
      "latin": "Zingel streber",
      "origin": "őshonos / védett",
      "group": "védett",
      "invasive": false,
      "image": "assets/fish/nemet-buco.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "nem fogható / védett",
      "dailyLimit": "0",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "fogassullo",
      "name": "Fogassüllő",
      "latin": "Sander lucioperca",
      "origin": "őshonos",
      "group": "ragadozó",
      "invasive": false,
      "image": "assets/fish/fogassullo.jpg",
      "closedStart": "03-02",
      "closedEnd": "04-30",
      "minSize": "30 cm",
      "dailyLimit": "3 db",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "kosullo",
      "name": "Kősüllő",
      "latin": "Sander volgensis",
      "origin": "őshonos",
      "group": "ragadozó",
      "invasive": false,
      "image": "assets/fish/kosullo.jpg",
      "closedStart": "03-02",
      "closedEnd": "06-30",
      "minSize": "25 cm",
      "dailyLimit": "3 db",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "balin",
      "name": "Balin",
      "latin": "Leuciscus aspius",
      "origin": "őshonos",
      "group": "ragadozó",
      "invasive": false,
      "image": "assets/fish/balin.jpg",
      "closedStart": "03-02",
      "closedEnd": "04-30",
      "minSize": "40 cm",
      "dailyLimit": "3 db",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "csuka",
      "name": "Csuka",
      "latin": "Esox lucius",
      "origin": "őshonos",
      "group": "ragadozó",
      "invasive": false,
      "image": "assets/fish/csuka.jpg",
      "closedStart": "02-02",
      "closedEnd": "03-31",
      "minSize": "40 cm",
      "dailyLimit": "3 db",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "harcsa",
      "name": "Harcsa",
      "latin": "Silurus glanis",
      "origin": "őshonos",
      "group": "ragadozó",
      "invasive": false,
      "image": "assets/fish/harcsa.jpg",
      "closedStart": "05-04",
      "closedEnd": "06-12",
      "minSize": "60 cm",
      "dailyLimit": "3 db",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "menyhal",
      "name": "Menyhal",
      "latin": "Lota lota",
      "origin": "őshonos",
      "group": "ragadozó",
      "invasive": false,
      "image": "assets/fish/menyhal.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "",
      "dailyLimit": "",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "sebes-pisztrang",
      "name": "Sebes pisztráng",
      "latin": "Salmo trutta",
      "origin": "őshonos / telepített",
      "group": "ragadozó",
      "invasive": false,
      "image": "assets/fish/sebes-pisztrang.jpg",
      "closedStart": "10-01",
      "closedEnd": "03-31",
      "minSize": "22 cm",
      "dailyLimit": "3 db",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "szivarvanyos-pisztrang",
      "name": "Szivárványos pisztráng",
      "latin": "Oncorhynchus mykiss",
      "origin": "idegenhonos / telepített",
      "group": "ragadozó",
      "invasive": false,
      "image": "assets/fish/szivarvanyos-pisztrang.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "",
      "dailyLimit": "",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "pataki-szajbling",
      "name": "Pataki szajbling",
      "latin": "Salvelinus fontinalis",
      "origin": "idegenhonos / telepített",
      "group": "ragadozó",
      "invasive": false,
      "image": "assets/fish/pataki-szajbling.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "",
      "dailyLimit": "",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "galoca",
      "name": "Galóca",
      "latin": "Hucho hucho",
      "origin": "őshonos / védett",
      "group": "védett",
      "invasive": false,
      "image": "assets/fish/galoca.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "nem fogható / védett",
      "dailyLimit": "0",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "lapi-poc",
      "name": "Lápi póc",
      "latin": "Umbra krameri",
      "origin": "őshonos / fokozottan védett",
      "group": "védett",
      "invasive": false,
      "image": "assets/fish/lapi-poc.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "nem fogható / védett",
      "dailyLimit": "0",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "naphal",
      "name": "Naphal",
      "latin": "Lepomis gibbosus",
      "origin": "inváziós / idegenhonos",
      "group": "inváziós",
      "invasive": true,
      "image": "assets/fish/naphal.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "",
      "dailyLimit": "",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "torpeharcsa",
      "name": "Törpeharcsa",
      "latin": "Ameiurus nebulosus",
      "origin": "inváziós / idegenhonos",
      "group": "inváziós",
      "invasive": true,
      "image": "assets/fish/torpeharcsa.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "",
      "dailyLimit": "",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "fekete-torpeharcsa",
      "name": "Fekete törpeharcsa",
      "latin": "Ameiurus melas",
      "origin": "inváziós / idegenhonos",
      "group": "inváziós",
      "invasive": true,
      "image": "assets/fish/fekete-torpeharcsa.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "",
      "dailyLimit": "",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "razbora",
      "name": "Razbóra",
      "latin": "Pseudorasbora parva",
      "origin": "inváziós / idegenhonos",
      "group": "inváziós",
      "invasive": true,
      "image": "assets/fish/razbora.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "",
      "dailyLimit": "",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "amurgeb",
      "name": "Amurgéb",
      "latin": "Perccottus glenii",
      "origin": "inváziós / idegenhonos",
      "group": "inváziós",
      "invasive": true,
      "image": "assets/fish/amurgeb.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "",
      "dailyLimit": "",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "kurta-baing",
      "name": "Kurta baing",
      "latin": "Leucaspius delineatus",
      "origin": "őshonos / védett",
      "group": "védett",
      "invasive": false,
      "image": "assets/fish/kurta-baing.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "nem fogható / védett",
      "dailyLimit": "0",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "okle",
      "name": "Ökle",
      "latin": "Rhodeus amarus",
      "origin": "őshonos / védett",
      "group": "védett",
      "invasive": false,
      "image": "assets/fish/okle.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "nem fogható / védett",
      "dailyLimit": "0",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "leanykoncer",
      "name": "Leánykoncér",
      "latin": "Rutilus virgo",
      "origin": "őshonos / védett",
      "group": "védett",
      "invasive": false,
      "image": "assets/fish/leanykoncer.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "nem fogható / védett",
      "dailyLimit": "0",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "gyongyos-koncer",
      "name": "Gyöngyös koncér",
      "latin": "Rutilus meidingeri",
      "origin": "őshonos / védett",
      "group": "védett",
      "invasive": false,
      "image": "assets/fish/gyongyos-koncer.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "nem fogható / védett",
      "dailyLimit": "0",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "fekete-suger",
      "name": "Fekete sügér",
      "latin": "Micropterus salmoides",
      "origin": "idegenhonos / telepített",
      "group": "ragadozó",
      "invasive": false,
      "image": "assets/fish/fekete-suger.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "",
      "dailyLimit": "",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "sarga-torpeharcsa",
      "name": "Sárga törpeharcsa",
      "latin": "Ameiurus natalis",
      "origin": "idegenhonos",
      "group": "inváziós",
      "invasive": true,
      "image": "assets/fish/sarga-torpeharcsa.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "",
      "dailyLimit": "",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "gambuzia",
      "name": "Gambúzia",
      "latin": "Gambusia holbrooki",
      "origin": "inváziós / idegenhonos",
      "group": "inváziós",
      "invasive": true,
      "image": "assets/fish/gambuzia.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "",
      "dailyLimit": "",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "kecsege",
      "name": "Kecsege",
      "latin": "Acipenser ruthenus",
      "origin": "őshonos / védett",
      "group": "védett",
      "invasive": false,
      "image": "assets/fish/kecsege.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "nem fogható / védett",
      "dailyLimit": "0",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "viza",
      "name": "Viza",
      "latin": "Huso huso",
      "origin": "őshonos / védett",
      "group": "védett",
      "invasive": false,
      "image": "assets/fish/viza.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "nem fogható / védett",
      "dailyLimit": "0",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "soregtok",
      "name": "Sőregtok",
      "latin": "Acipenser stellatus",
      "origin": "őshonos / védett",
      "group": "védett",
      "invasive": false,
      "image": "assets/fish/soregtok.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "nem fogható / védett",
      "dailyLimit": "0",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "vagotok",
      "name": "Vágótok",
      "latin": "Acipenser gueldenstaedtii",
      "origin": "őshonos / védett",
      "group": "védett",
      "invasive": false,
      "image": "assets/fish/vagotok.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "nem fogható / védett",
      "dailyLimit": "0",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "simatok",
      "name": "Simatok",
      "latin": "Acipenser nudiventris",
      "origin": "őshonos / védett",
      "group": "védett",
      "invasive": false,
      "image": "assets/fish/simatok.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "nem fogható / védett",
      "dailyLimit": "0",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "afrikai-harcsa",
      "name": "Afrikai harcsa",
      "latin": "Clarias gariepinus",
      "origin": "idegenhonos / halgazdasági",
      "group": "egyéb",
      "invasive": false,
      "image": "assets/fish/afrikai-harcsa.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "",
      "dailyLimit": "",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "tilapia",
      "name": "Tilápia",
      "latin": "Oreochromis niloticus",
      "origin": "idegenhonos / halgazdasági",
      "group": "egyéb",
      "invasive": false,
      "image": "assets/fish/tilapia.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "",
      "dailyLimit": "",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "aranyhal",
      "name": "Aranyhal",
      "latin": "Carassius auratus",
      "origin": "idegenhonos",
      "group": "egyéb",
      "invasive": false,
      "image": "assets/fish/aranyhal.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "",
      "dailyLimit": "",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "koiponty",
      "name": "Koiponty",
      "latin": "Cyprinus carpio koi",
      "origin": "idegenhonos / díszhal",
      "group": "egyéb",
      "invasive": false,
      "image": "assets/fish/koiponty.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "",
      "dailyLimit": "",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "tavi-szaibling",
      "name": "Tavi szaibling",
      "latin": "Salvelinus alpinus",
      "origin": "idegenhonos / telepített",
      "group": "ragadozó",
      "invasive": false,
      "image": "assets/fish/tavi-szaibling.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "",
      "dailyLimit": "",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    },
    {
      "id": "lenai-tok",
      "name": "Lénai tok",
      "latin": "Acipenser baerii",
      "origin": "idegenhonos / telepített",
      "group": "egyéb",
      "invasive": false,
      "image": "assets/fish/lenai-tok.jpg",
      "closedStart": "",
      "closedEnd": "",
      "minSize": "",
      "dailyLimit": "",
      "ruleNote": "Szerkeszthető adat. Helyi horgászrend alapján pontosítható."
    }
  ],
  "waters": [
    {
      "id": "balaton",
      "name": "Balaton",
      "coords": "",
      "image": "assets/water/balaton.jpg",
      "note": ""
    },
    {
      "id": "velencei-to",
      "name": "Velencei-tó",
      "coords": "",
      "image": "assets/water/velencei-to.jpg",
      "note": ""
    },
    {
      "id": "tisza-to",
      "name": "Tisza-tó",
      "coords": "",
      "image": "assets/water/tisza-to.jpg",
      "note": ""
    },
    {
      "id": "duna",
      "name": "Duna",
      "coords": "",
      "image": "assets/water/duna.jpg",
      "note": ""
    },
    {
      "id": "tisza",
      "name": "Tisza",
      "coords": "",
      "image": "assets/water/tisza.jpg",
      "note": ""
    },
    {
      "id": "rackevei-soroksari-duna",
      "name": "Ráckevei-Soroksári Duna",
      "coords": "",
      "image": "assets/water/rackevei-soroksari-duna.jpg",
      "note": ""
    },
    {
      "id": "korosok",
      "name": "Körösök",
      "coords": "",
      "image": "assets/water/korosok.jpg",
      "note": ""
    },
    {
      "id": "holtag",
      "name": "Holtág",
      "coords": "",
      "image": "assets/water/holtag.jpg",
      "note": ""
    },
    {
      "id": "csatorna",
      "name": "Csatorna",
      "coords": "",
      "image": "assets/water/csatorna.jpg",
      "note": ""
    },
    {
      "id": "banyato",
      "name": "Bányató",
      "coords": "",
      "image": "assets/water/banyato.jpg",
      "note": ""
    },
    {
      "id": "patak",
      "name": "Patak",
      "coords": "",
      "image": "assets/water/patak.jpg",
      "note": ""
    },
    {
      "id": "intenziv-to",
      "name": "Intenzív tó",
      "coords": "",
      "image": "assets/water/intenziv-to.jpg",
      "note": ""
    }
  ],
  "db": {
    "methods": [
      {
        "id": "feeder",
        "name": "Feeder",
        "category": "Fenekező / feeder",
        "note": ""
      },
      {
        "id": "method-feeder",
        "name": "Method feeder",
        "category": "Fenekező / feeder",
        "note": ""
      },
      {
        "id": "picker",
        "name": "Picker",
        "category": "Fenekező / feeder",
        "note": ""
      },
      {
        "id": "fenekezo",
        "name": "Fenekező",
        "category": "Fenekező",
        "note": ""
      },
      {
        "id": "bojlis",
        "name": "Bojlis",
        "category": "Pontyos / nagyhalas",
        "note": ""
      },
      {
        "id": "uszos",
        "name": "Úszós",
        "category": "Úszós",
        "note": ""
      },
      {
        "id": "match",
        "name": "Matchbotos",
        "category": "Úszós",
        "note": ""
      },
      {
        "id": "bolognai",
        "name": "Bolognai",
        "category": "Úszós / folyóvízi",
        "note": ""
      },
      {
        "id": "spicc",
        "name": "Spiccbotos",
        "category": "Úszós",
        "note": ""
      },
      {
        "id": "rakos",
        "name": "Rakós botos",
        "category": "Úszós / verseny",
        "note": ""
      },
      {
        "id": "pergetes",
        "name": "Pergetés",
        "category": "Ragadozóhalas",
        "note": ""
      },
      {
        "id": "dropshot",
        "name": "Dropshot",
        "category": "Ragadozóhalas",
        "note": ""
      },
      {
        "id": "ul",
        "name": "Ultra light / UL",
        "category": "Ragadozóhalas",
        "note": ""
      },
      {
        "id": "harcsazas",
        "name": "Harcsázás",
        "category": "Ragadozóhalas",
        "note": ""
      },
      {
        "id": "legyezes",
        "name": "Legyezés",
        "category": "Műlegyes",
        "note": ""
      }
    ],
    "lines": [
      {
        "id": "mono-020",
        "name": "0.20 mm monofil",
        "category": "Főzsinór",
        "note": ""
      },
      {
        "id": "mono-025",
        "name": "0.25 mm monofil",
        "category": "Főzsinór",
        "note": ""
      },
      {
        "id": "fluoro-018",
        "name": "0.18 mm fluorocarbon",
        "category": "Előkezsinór",
        "note": ""
      }
    ],
    "hooks": [
      {
        "id": "guru-qm1-12",
        "name": "Guru QM1 #12",
        "category": "Method horog",
        "note": ""
      }
    ],
    "baits": [
      {
        "id": "wafter-eper",
        "name": "Wafter 8 mm – eper",
        "category": "Wafter",
        "note": ""
      },
      {
        "id": "csonti",
        "name": "Csonti",
        "category": "Élő csali",
        "note": ""
      }
    ],
    "groundbaits": [
      {
        "id": "method-edes",
        "name": "Édes method mix",
        "category": "Method etető",
        "note": ""
      }
    ],
    "accessories": [
      {
        "id": "method-kosar-30",
        "name": "30 g method kosár",
        "category": "Kosár / ólom",
        "note": ""
      }
    ]
  }
};